/* loader.c — user-space loader that attaches GCOS's own sched_ext scheduler
 * (gcos/osprims/ebpf/scx_gcos.bpf.c) so the kernel arbitrates the CPU with OUR
 * scheduler. This is the piece that turns scx_gcos.bpf.c into a running kernel
 * scheduler.
 *
 * VERIFIED IN CI: requires Linux >= 6.12 with CONFIG_SCHED_CLASS_EXT and the
 * scx/libbpf toolchain. The `scx-ext` CI job builds + runs exactly this loader on
 * a sched_ext-capable runner and confirms the scheduler attaches
 * (/sys/kernel/sched_ext/state == enabled, ops == gcos). A plain dev box (colima
 * 6.8) lacks sched_ext; `scripts/scx/run.sh` reproduces the build+load on a 6.12+
 * host in one command. Written against the documented sched_ext libbpf pattern.
 *
 * Build: see scripts/scx/Makefile (generates scx_gcos.skel.h via bpftool).
 */
#include <stdio.h>
#include <signal.h>
#include <unistd.h>
#include <libgen.h>
#include <bpf/bpf.h>
#include <bpf/libbpf.h>
#include <scx/common.h>            /* UEI_REPORT, from the sched-ext/scx headers */
#include "scx_gcos.skel.h"        /* generated by `bpftool gen skeleton`        */

static volatile int exit_req;
static void on_signal(int sig) { (void)sig; exit_req = 1; }

static int libbpf_print(enum libbpf_print_level lvl, const char *fmt, va_list ap) {
    return vfprintf(stderr, fmt, ap);
}

int main(void)
{
    struct scx_gcos *skel;
    struct bpf_link *link;

    libbpf_set_print(libbpf_print);
    signal(SIGINT, on_signal);
    signal(SIGTERM, on_signal);

    skel = scx_gcos__open();
    if (!skel) { fprintf(stderr, "scx_gcos__open failed\n"); return 1; }

    if (scx_gcos__load(skel)) {
        fprintf(stderr, "scx_gcos__load failed (need root, clang/libbpf, BTF)\n");
        scx_gcos__destroy(skel);
        return 1;
    }

    /* Attaching the struct_ops makes gcos_ops the live CPU scheduler. */
    link = bpf_map__attach_struct_ops(skel->maps.gcos_ops);
    if (!link) {
        fprintf(stderr, "attach failed — need Linux >= 6.12 with sched_ext "
                        "(CONFIG_SCHED_CLASS_EXT) and CAP_SYS_ADMIN/root\n");
        scx_gcos__destroy(skel);
        return 1;
    }

    fprintf(stderr, "scx_gcos LOADED — the GCOS scheduler is now arbitrating the "
                    "CPU (check /sys/kernel/sched_ext/state). Ctrl-C to detach.\n");

    /* Stay attached until interrupted or the BPF scheduler exits (its watchdog
     * reverts to the default scheduler on error, so a bug can't wedge the box). */
    while (!exit_req && !UEI_EXITED(skel, uei))
        sleep(1);

    UEI_REPORT(skel, uei);
    bpf_link__destroy(link);
    scx_gcos__destroy(skel);
    fprintf(stderr, "scx_gcos detached; kernel reverted to the default scheduler.\n");
    return 0;
}
